kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    labels:
      app: dht-server
    name: dht-server
    namespace: node-1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: dht-server
    template:
      metadata:
        labels:
          app: dht-server
      spec:
        nodeSelector:
          target: node-1
        containers:
          - name: dht-server
            securityContext:
              privileged: true
            image: floreks/dht-server
            imagePullPolicy: Always
            ports:
              - containerPort: 3000
                protocol: TCP
            volumeMounts:
              - mountPath: /sys/class/gpio
                name:      sys-class-gpio
              - mountPath: /sys/devices
                name:      sys-devices
            args:
              # Uncomment this if you want to change port
              # - --port=3001
        volumes:
          - name:     sys-class-gpio
            hostPath:
              path:   /sys/class/gpio
          - name:     sys-devices
            hostPath:
              path:   /sys/devices
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: dht-server
    name: dht-server
    namespace: node-1
  spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: dht-server
