kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    labels:
      app: kubepi-monitor
    name: kubepi-monitor
    namespace: node-1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kubepi-monitor
    template:
      metadata:
        labels:
          app: kubepi-monitor
      spec:
        nodeSelector:
          target: node-1
        containers:
          - name: kubepi-monitor
            image: floreks/kubepi-monitor
            imagePullPolicy: Always
            ports:
              - containerPort: 80
                protocol: TCP
            args:
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: kubepi-monitor
    name: kubepi-monitor
    namespace: node-1
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
    selector:
      app: kubepi-monitor
